FROM openjdk:11-jdk-slim

COPY . /app/

COPY app/__init__.py /app
COPY app/main.py /app/
COPY app/helper.py /app/

WORKDIR /app

ENV SPARK_XML_VERSION=0.15.0
ENV INPUT_DIR="/app/input"
ENV OUTPUT_DIR="/app/output"
ENV TMP_DIR="/app/tmp"
ENV JAR_PATH="/jars/spark-xml_2.12-${SPARK_XML_VERSION}.jar"

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip && \
    apt-get install -y wget && \
    apt-get clean

RUN mkdir -p /jars && \
    wget -P /jars https://repo1.maven.org/maven2/com/databricks/spark-xml_2.12/${SPARK_XML_VERSION}/spark-xml_2.12-${SPARK_XML_VERSION}.jar

VOLUME ["input", "output"]

RUN pip install -r requirements.txt && \
    pip install -r requirements-test.txt


CMD ["pytest", "tests", "-s", "-vvv"]
